esphome:
  name: pzem1
  friendly_name: pzem1

esp32:
  board: esp32dev
  framework:
    # type: esp-idf
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret pzem1_api_key

ota:
  - platform: esphome
    password: !secret pzem1_ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pzem1 Fallback Hotspot"
    password: !secret pzem1_ap_pass

captive_portal: 

web_server:
  port: 80

# Додаємо явне визначення UART з ID
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 2

# Додаємо Modbus контролер, щоб мати до нього доступ через lambda
modbus:
  - id: pzem_modbus
    uart_id: uart_bus

modbus_controller:
  - id: pzem_ctrl
    address: 0x01
    modbus_id: pzem_modbus
    setup_priority: -10


select:
  - platform: modbus_controller
    modbus_controller_id: pzem_ctrl
    name: "PZEM Shunt Scale Hardware"
    address: 0x0003  # Регістр вибору шунта
    value_type: U_WORD
    optimistic: true
    optionsmap:
      "100A": 1
      "200A": 2
      "300A": 0
      "50A": 3

sensor:
  - platform: pzemdc
    current:
      name: "pzem1 Current"
      id: pzem1_current
      filters:
        - multiply: 1.0 # Тут можна буде додати калібрування пізніше
    voltage:
      name: "pzem1 Voltage"
      id: pzem1_voltage
    power:
      name: "pzem1 Power"
      id: pzem1_power
    energy:
      name: "pzem1 Energy"
      id: pzem1_energy
    update_interval: 1s # Зменшив до 1с для точнішого Coulomb Counting